name: 05-1-filters-activity-types
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main 

jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: print pull request details
          run: echo" Running when a pull request is opened or synchronized on the main branch"
