name: 05-1-filters-activity-types
on: 
  workflow_dispatch

jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: print pull request details
          run: echo "Running when a pull request is opened or synchronized on the main branch"
